- hosts: localhost
  roles:
    - role: check/updates
      tags: check-updates
    - role: check/clock
      tags: check-clock
    - role: check/diskspace
      tags: check-diskspace
    - role: check/openstack/logging
      tags: check-openstack-logging
    - role: check/openstack/cinder
      tags: check-openstack-cinder
    - role: check/openstack/keystone
      tags: check-openstack-keystone
