- name: get metering_connection setting
  os_config:
    project: ceilometer
    options:
      - group: database
        name: metering_connection
        deprecated_group: database
        deprecated_name: connection
  register: ceilometer_connection
  ignore_errors: true

- name: get metering_time_to_live setting
  os_config:
    project: ceilometer
    options:
      - group: database
        name: metering_time_to_live
        deprecated_group: database
        deprecated_name: time_to_live
        default: 0
  register: ceilometer_ttl
  ignore_errors: true

- name: check metering_time_to_live setting
  assert:
    nonfatal: true
    that: ceilometer_ttl.config.database.metering_time_to_live|int > 0
    msg: "metric expiration is not configured"
  when: >
    ceilometer_connection.config.database.metering_connection
  ignore_errors: "{{ continue_on_error|default(false)|bool }}"

- name: get metering database size
  mongo_query:
    connection: "{{ ceilometer_connection.config.database.metering_connection }}"
    query: "db.stats()"
  register: mongo_db_size
  when: >
    'database' in ceilometer_connection.config

- name: check metering database size
  assert:
    nonfatal: true
    that: mongo_db_size.results.storageSize < mongo_db_size_limit|int
    msg: "metering database is large ({{ mongo_db_size.results.storageSize }} bytes); have you set a ceilometer_ttl?"
  when: not mongo_db_size|skipped
  ignore_errors: "{{ continue_on_error|default(false)|bool }}"
