- name: get list of enabled backends
  os_config:
    project: cinder
    options:
      - name: enabled_backends
        type: list
  register: cinder_backends
  ignore_errors: true

- when: cinder_backends|success
  block:
    - name: get volume_driver for each backend
      os_config:
        project: cinder
        options:
          - group: "{{ item }}"
            name: volume_driver
      register: volume_drivers
      when: item != ""
      with_items: "{{ cinder_backends.config.enabled_backends }}"

    - assert:
        nonfatal: true
        that: not item.config[item.item].volume_driver.endswith('LVMVolumeDriver')
        msg: "LVM volume driver is enabled for backend {{ item.item }}"
      when: not item|skipped
      with_items: "{{ volume_drivers.results }}"
      ignore_errors: "{{ continue_on_error|default(false)|bool }}"
