---
- name: check if ntpd is active
  command: systemctl is-enabled ntpd
  register: ntpd_active
  failed_when: false
  changed_when: false

- name: check if chronyd is active
  command: systemctl is-enabled chronyd
  register: chronyd_active
  failed_when: false
  changed_when: false

- name: check if both ntp services are active
  assert:
    that: not (chronyd_active.rc != 0 and ntpd_active.rc != 0)
    msg: both chronyd and ntpd appear to be active.
  ignore_errors: "{{ continue_on_error|default(false)|bool }}"

- name: check if neither service is active
  assert:
    that: (chronyd_active.rc == 0 or ntpd_active.rc == 0)
    msg: "no ntp service is running"
  ignore_errors: "{{ continue_on_error|default(false)|bool }}"

- name: get clock skew from ntpd
  ntpd_clock_skew:
  register: clock_skew_ntpd
  when: ntpd_active.rc == 0

- name: get clock skew from chronyd
  chronyd_clock_skew:
  register: clock_skew_chronyd
  when: chronyd_active.rc == 0

- name: set clock_skew fact
  set_fact:
    clock_skew: >
      {% if ntpd_active.rc == 0 %}{{ clock_skew_ntpd}}{% else -%}
      {{ clock_skew_chronyd }}{% endif %}

- name: check if clock is synchronized
  assert:
    that: >
      clock_skew.clock.synchronized
    msg: clock is not synchronized
  ignore_errors: "{{ continue_on_error|default(false)|bool }}"

- name: check ntp offset
  assert:
    that: >
      clock_skew.clock.offset < clock_skew_limit|default(1)
    msg: clock offset is too large
  when: clock_skew.clock.synchronized
  ignore_errors: "{{ continue_on_error|default(false)|bool }}"
