- hosts: localhost
  roles:
    - module/assert

- hosts: all
  name: basic system tests
  tags:
    - check-basic
  roles:
    - role: check/updates
      tags: check-updates
    - role: check/clock
      tags: check-clock
    - role: check/diskspace
      tags: check-diskspace

- hosts: all
  name: pacemaker tests
  tags:
    - check-pacemaker
  roles:
    - role: check/pacemaker/fencing

- hosts: all
  name: openstack tests
  tags:
    - check-openstack
  roles:
    - role: check/openstack/logging
      tags: check-openstack-logging
    - role: check/openstack/cinder
      tags: check-openstack-cinder
    - role: check/openstack/keystone
      tags: check-openstack-keystone
    - role: check/openstack/ceilometer
      tags: check-openstack-ceilometer
