- hosts: localhost
  roles:
    - module/assert

- hosts: all
  name: basic system tests
  tags:
    - check-system
  roles:
    - role: check/system/rhel
      tags: check-system-rhel
    - role: check/system/updates
      tags: check-system-updates
    - role: check/system/clock
      tags: check-system-clock
    - role: check/system/diskspace
      tags: check-system-diskspace

- hosts: all
  name: pacemaker tests
  tags:
    - check-pacemaker
  roles:
    - role: check/pacemaker/fencing

- hosts: all
  name: openstack tests
  tags:
    - check-openstack
  roles:
    - role: check/openstack/logging
      tags: check-openstack-logging
    - role: check/openstack/cinder
      tags: check-openstack-cinder
    - role: check/openstack/keystone
      tags: check-openstack-keystone
    - role: check/openstack/ceilometer
      tags: check-openstack-ceilometer
