---
- name: check for available package updates
  command: dnf check-update
  register: check_update
  failed_when: check_update.rc == 100
  changed_when: false
  ignore_errors: true

- assert:
    that: not check_update|failed
    msg: "There are available uninstalled updates."
  ignore_errors: "{{ continue_on_error|default(false)|bool }}"
